---
  - hosts: frontend
    become: yes
    
    tasks:
      - name: Crear directorio de imagenes
        file:
          path: /usr/images
          state: directory
          recurse: yes
      - name: Copiar imagen Frontend
        copy:
          src: unir-frontend.tar
          dest: /usr/images/unir-frontend.tar
      - name: Borrar contenedor anterior
        command:
          command: if [ -n "$(docker container ls -a -q)" ]; then docker container rm -v -f $(docker container ls -a -q); fi
      - name: Borrar imagen anterior
        command:
          command: if [ -n "$(docker images unir/frontend -q)" ]; then docker rmi -f $(docker images unir/front -q); fi
      - name: Cargar imagen Frontend
        command:
          chdir: /usr/images
          command: docker load < unir-frontend.tar
      - name: Correr la imagen Frontend
        command:
          chdir: /usr/images
          command: docker run --env NODE_ENV=prod --env PRO_HOST={{ lookup('env', 'PRO_HOST') }} --env TOKEN_KEY={{ lookup('env', 'TOKEN_KEY_PRO') }} --name unir/front -p8080:8080 -dt unir/front