---
  - hosts: frontend
    become: yes
    
    tasks:
      - name: Crear directorio de imagenes
        file:
          path: /usr/images
          state: directory
          recurse: yes
      - name: Copiar imagen
        copy:
          src: unir-frontend.tar
          dest: /usr/images/unir-frontend.tar
      - name: Borrar los contenedores actuales
        command:
          command: if [ -n "$(docker container ls -a -q)" ]; then docker container rm -f $(docker container ls -a -q); fi
      - name: Borrar las imagenes actuales
        command:
          command: if [ -n "$(docker images unir/frontend -q)" ]; then docker rmi -f $(docker images unir/frontend -q); fi
      - name: Cargar imagen
        command:
          chdir: /usr/images
          command: docker load < unir-frontend.tar
      - name: Correr la imagen
        command:
          chdir: /usr/images
          command: docker run --env NODE_ENV=pro --env PRO_HOST={{ lookup('env', 'PRO_HOST') }} --env TOKEN_KEY=tost4da --name frontend -p8080:8080 -dt unir/frontend

