# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class Balance(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, account_id: int=None, current_balance: int=None, last_trasnaction_date: str=None):  # noqa: E501
        """Balance - a model defined in Swagger

        :param account_id: The account_id of this Balance.  # noqa: E501
        :type account_id: int
        :param current_balance: The current_balance of this Balance.  # noqa: E501
        :type current_balance: int
        :param last_trasnaction_date: The last_trasnaction_date of this Balance.  # noqa: E501
        :type last_trasnaction_date: str
        """
        self.swagger_types = {
            'account_id': int,
            'current_balance': int,
            'last_trasnaction_date': str
        }

        self.attribute_map = {
            'account_id': 'account_id',
            'current_balance': 'current_balance',
            'last_trasnaction_date': 'last_trasnaction_date'
        }

        self._account_id = account_id
        self._current_balance = current_balance
        self._last_trasnaction_date = last_trasnaction_date

    @classmethod
    def from_dict(cls, dikt) -> 'Balance':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The Balance of this Balance.  # noqa: E501
        :rtype: Balance
        """
        return util.deserialize_model(dikt, cls)

    @property
    def account_id(self) -> int:
        """Gets the account_id of this Balance.


        :return: The account_id of this Balance.
        :rtype: int
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id: int):
        """Sets the account_id of this Balance.


        :param account_id: The account_id of this Balance.
        :type account_id: int
        """

        self._account_id = account_id

    @property
    def current_balance(self) -> int:
        """Gets the current_balance of this Balance.


        :return: The current_balance of this Balance.
        :rtype: int
        """
        return self._current_balance

    @current_balance.setter
    def current_balance(self, current_balance: int):
        """Sets the current_balance of this Balance.


        :param current_balance: The current_balance of this Balance.
        :type current_balance: int
        """

        self._current_balance = current_balance

    @property
    def last_trasnaction_date(self) -> str:
        """Gets the last_trasnaction_date of this Balance.


        :return: The last_trasnaction_date of this Balance.
        :rtype: str
        """
        return self._last_trasnaction_date

    @last_trasnaction_date.setter
    def last_trasnaction_date(self, last_trasnaction_date: str):
        """Sets the last_trasnaction_date of this Balance.


        :param last_trasnaction_date: The last_trasnaction_date of this Balance.
        :type last_trasnaction_date: str
        """

        self._last_trasnaction_date = last_trasnaction_date
