# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class TransactionData(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, amount: int=None, description: str=None):  # noqa: E501
        """TransactionData - a model defined in Swagger

        :param amount: The amount of this TransactionData.  # noqa: E501
        :type amount: int
        :param description: The description of this TransactionData.  # noqa: E501
        :type description: str
        """
        self.swagger_types = {
            'amount': int,
            'description': str
        }

        self.attribute_map = {
            'amount': 'amount',
            'description': 'description'
        }

        self._amount = amount
        self._description = description

    @classmethod
    def from_dict(cls, dikt) -> 'TransactionData':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The TransactionData of this TransactionData.  # noqa: E501
        :rtype: TransactionData
        """
        return util.deserialize_model(dikt, cls)

    @property
    def amount(self) -> int:
        """Gets the amount of this TransactionData.


        :return: The amount of this TransactionData.
        :rtype: int
        """
        return self._amount

    @amount.setter
    def amount(self, amount: int):
        """Sets the amount of this TransactionData.


        :param amount: The amount of this TransactionData.
        :type amount: int
        """

        self._amount = amount

    @property
    def description(self) -> str:
        """Gets the description of this TransactionData.


        :return: The description of this TransactionData.
        :rtype: str
        """
        return self._description

    @description.setter
    def description(self, description: str):
        """Sets the description of this TransactionData.


        :param description: The description of this TransactionData.
        :type description: str
        """

        self._description = description
