CREATE DATABASE TFMUNIRBD;
USE TFMUNIRBD;

CREATE TABLE USER (
    USERID INT(6) AUTO_INCREMENT,
    USERNAME VARCHAR(16) NOT NULL,
    FULLNAME VARCHAR(64) NOT NULL,
    PASSWORD VARCHAR(512) NOT NULL,
    CREATIONDATE TIMESTAMP NOT NULL,
    PRIMARY KEY (USERID)    
);

CREATE TABLE ACCOUNT(
    ACCOUNTID INT(6) AUTO_INCREMENT,
    ACCOUNTNUMBER VARCHAR(64) NOT NULL,
    USERID INT(6),
    PRIMARY KEY (ACCOUNTID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID) 
);

CREATE TABLE TRANSACTIONS(
    TRANSACTIONID INT(6) AUTO_INCREMENT,
    USERID INT(6),
    ACCOUNTID INT(6),
    AMOUNT INT(32) NOT NULL,
    DESCRIPTION VARCHAR(128),
    CURRENTBALANCE INT(32) NOT NULL,
    TRANSACTIONDATE TIMESTAMP  NOT NULL,
    PRIMARY KEY (TRANSACTIONID),
    FOREIGN KEY (USERID) REFERENCES USER(USERID)
);